
spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 200MB
    datasource:
        name: source
        url: jdbc:mysql://120.79.132.62:3306/myinsurance?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: password
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#    mvc:
#        view:
#            prefix: /
#            suffix: .html
    jmx:
        enabled: false

    mail:
        default-encoding: UTF-8
        host: smtp.qq.com
        username: 499867382@qq.com
        password: uraukppoeimcbgij
        properties:
            mail:
                smpt:
                    auth: true
                    starttlls:
                        enable: true
                        required: true


mybatis:
    mapperLocations: classpath:mapping/*.xml
    typeAliasesPackage: com.cq.myinsurance.pojo

#logging:
#    level:
#        com.iforce.zingrow.dao.IUserDao: INFO
#